DROP DATABASE ProjetoUnivesp2021;

CREATE DATABASE IF NOT EXISTS ProjetoUnivesp2021;

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.HOSPITAL(
   HID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   HNOME VARCHAR(255) NOT NULL,
   HUF TINYINT(2) NOT NULL,
   HCIDADE VARCHAR(50) NOT NULL,
   HCEP VARCHAR(8) NOT NULL,
   HENDERECO VARCHAR(150) NOT NULL,
   HCOMPLEMENTO VARCHAR(150),
   HTELEFONE BIGINT(14) NOT NULL,
   HISPRONTOSOCORRO BOOLEAN NOT NULL DEFAULT FALSE,
   HATIVADO ENUM('T', 'F', 'D') DEFAULT 'T'
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.ESPECIALIDADES(
    EID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    HNOME VARCHAR(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.MEDICOS(
    MID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    MNOME VARCHAR(255) NOT NULL,
    EID INT UNSIGNED NOT NULL,
    HID INT UNSIGNED NOT NULL,
    MATIVADO ENUM('T', 'F', 'D') DEFAULT 'T' NOT NULL
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.USUARIOS(
    UID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    UNOME VARCHAR(255) NOT NULL,
    UEMAIL VARCHAR(100) NOT NULL UNIQUE,
    UPASSWORD VARCHAR(80) NOT NULL,
    UCPF CHAR(11) NOT NULL UNIQUE,
    UUF TINYINT(2) NOT NULL,
    UCIDADE VARCHAR(50) NOT NULL,
    UCEP VARCHAR(8) NOT NULL,
    UENDERECO VARCHAR(150) NOT NULL,
    UCOMPLEMENTO VARCHAR(150),
    UATIVADO ENUM('T', 'F', 'D') DEFAULT 'T' NOT NULL
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.AGENDAS(
    AID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    UID BIGINT UNSIGNED NOT NULL,
    MID BIGINT UNSIGNED NOT NULL,
    HID BIGINT UNSIGNED NOT NULL,
    ADATA DATETIME NOT NULL,
    AATIVADO ENUM('T', 'D') DEFAULT 'T' NOT NULL
)