CREATE DATABASE IF NOT EXISTS ProjetoUnivesp2021;

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.LOJA (
   LID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   LNOME VARCHAR(20) NOT NULL,
   PLANO CHAR(1) NOT NULL,
   ATIVADO TINYINT(4)
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.USUARIOS(
   UID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   LID INT UNSIGNED NOT NULL,
   UNAME VARCHAR(30) NOT NULL,
   UEMAIL VARCHAR(100) NOT NULL UNIQUE,
   UPASSWORD VARCHAR(80) NOT NULL,
   UISADMIN TINYINT(4) NOT NULL DEFAULT 0,
   UTOKEN VARCHAR(33),
   ATIVADO TINYINT(4) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.PRODUTOS(
    PID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    LID INT UNSIGNED NOT NULL,
    PNOME VARCHAR(90) NOT NULL,
    PDESC VARCHAR(150) NOT NULL,
    PUNIDADE_MEDIDA VARCHAR(4) NOT NULL DEFAULT '',
    PISVALIDADE TINYINT(4) NOT NULL DEFAULT 0,
    ATIVADO TINYINT(4) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.ESTOQUE(
    EID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PID BIGINT UNSIGNED NOT NULL,
    EQUANTIDADE DECIMAL(6,2) UNSIGNED NOT NULL,
    EVALORCOMPRA DECIMAL(6,2) UNSIGNED NOT NULL,
    EVALORVENDA DECIMAL(6,2) UNSIGNED NOT NULL,
    EVALIDADE DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ProjetoUnivesp2021.ORDENS(
    OID BIGINT UNSIGNED KEY AUTO_INCREMENT,
    EID BIGINT UNSIGNED NOT NULL,
    ODATA DATETIME NOT NULL,
    OTIPO ENUM('C', 'V', 'D'), # Compra, Venda, Descarte
    OQUANTIDADE DECIMAL(6,2) UNSIGNED NOT NULL,
    OVALOR DECIMAL(6,2) UNSIGNED NOT NULL
);